/** Aliases are inherited from DSH in-app; the portal uses the same built-in values. */
export const portalTheme = `
body{--dsw-alias-bg-base:#fff;--dsw-alias-bg-layer-1:#fff;--dsw-alias-bg-layer-2:#fff;--dsw-alias-label-primary:#0f1115;--dsw-alias-label-secondary:#61666b;--dsw-alias-label-tertiary:#7c838b;--dsw-alias-label-primary-foreground:#fff;--dsw-alias-border-l2:#0000001a;--dsw-alias-button-primary-fill:#0f1115;--dsw-alias-button-primary-hover:#43454a;--dsw-alias-button-floating-fill:#fff;--dsw-alias-button-floating-hover:#f3f4f6;--dsw-alias-button-ghost-active-fill:#ebeef2;--totp-error:#ec1313}
body[data-ds-dark-theme]{--dsw-alias-bg-base:#151517;--dsw-alias-bg-layer-1:#232324;--dsw-alias-bg-layer-2:#2c2c2e;--dsw-alias-label-primary:#f9fafb;--dsw-alias-label-secondary:#cfd3d6;--dsw-alias-label-tertiary:#a6abb2;--dsw-alias-label-primary-foreground:#0f1115;--dsw-alias-border-l2:#ffffff1f;--dsw-alias-button-primary-fill:#f9fafb;--dsw-alias-button-primary-hover:#ebeef2;--dsw-alias-button-floating-fill:#2c2c2e;--dsw-alias-button-floating-hover:#353638;--dsw-alias-button-ghost-active-fill:#43454a;--totp-error:#f87171}`;

export const panelCss = `
:host{font:14px/1.6 var(--dsw-font-family,system-ui,-apple-system,"Segoe UI",sans-serif);color:var(--dsw-alias-label-primary,#0f1115)}
*{box-sizing:border-box}[hidden]{display:none!important}button,input{font:inherit}button{cursor:pointer;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:10px;padding:9px 14px;min-height:38px;color:var(--dsw-alias-label-primary,#0f1115);background:var(--dsw-alias-button-floating-fill,#fff);transition:background .15s}
button:hover{background:var(--dsw-alias-button-floating-hover,#f3f4f6)}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible{outline:2px solid var(--dsw-alias-button-info-fill,#4176e6);outline-offset:3px}
button.primary{background:var(--dsw-alias-button-primary-fill,#0f1115);color:var(--dsw-alias-label-primary-foreground,#fff);border-color:transparent}button.primary:hover{background:var(--dsw-alias-button-primary-hover,#43454a)}
nav{display:flex;gap:6px}dialog{font:14px/1.6 var(--dsw-font-family,system-ui);width:min(456px,calc(100vw - 32px));max-height:calc(100dvh - 48px);overflow:auto;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:20px;padding:28px;background:var(--dsw-alias-bg-layer-2,#fff);color:var(--dsw-alias-label-primary,#0f1115);box-shadow:var(--dsw-elevation-panel,0 16px 64px #0002)}dialog::backdrop{background:#0007}
h3{font-size:20px;line-height:1.4;font-weight:600;margin:0 0 8px}p{margin:0 0 16px;text-wrap:pretty}small,.secondary{color:var(--dsw-alias-label-secondary,#61666b)}small{font-size:12px}.eyebrow{color:var(--dsw-alias-label-tertiary,#7c838b);font-size:12px;margin-bottom:18px}.divider{height:1px;background:var(--dsw-alias-border-l2,#0000001a);margin:20px 0}
label{display:block;font-size:13px;margin:16px 0 7px;color:var(--dsw-alias-label-secondary,#61666b)}input{width:100%;min-width:0;padding:11px 13px;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:10px;color:var(--dsw-alias-label-primary,#0f1115);background:var(--dsw-alias-bg-layer-1,#fff)}input.code{height:76px;background:var(--dsw-alias-bg-layer-2,#fff);font:500 34px/1 ui-monospace,SFMono-Regular,Consolas,monospace;font-variant-numeric:tabular-nums;letter-spacing:.32em;text-indent:.32em;text-align:center;border-radius:12px;transition:border-color .15s,box-shadow .15s}input.code::placeholder{color:var(--dsw-alias-label-tertiary,#979da6);opacity:.5}input.code:hover:not(:disabled){border-color:var(--dsw-alias-label-tertiary,#979da6)}input.code:focus-visible{outline:none;border-color:var(--dsw-alias-button-info-fill,#4176e6);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-button-info-fill,#4176e6) 16%,transparent)}
.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.error{font-size:13px;color:var(--totp-error,var(--dsw-static-red-500,#ef4444));white-space:pre-wrap;min-height:20px;margin-top:12px}.qr{display:block;width:224px;height:224px;max-width:100%;margin:20px auto;background:#fff;border:8px solid #fff;border-radius:12px}.recovery-codes{font:12px/1.9 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;white-space:pre-wrap;border-radius:10px;padding:14px;background:var(--dsw-alias-bg-layer-1,#fff);border:1px solid var(--dsw-alias-border-l2,#0000001a);max-height:230px;overflow:auto}.binding-note{font-size:13px;color:var(--dsw-alias-label-secondary,#61666b)}
/* Control-page hierarchy: one protection summary, a quiet credential list, and lock actions. */
dialog{container-type:inline-size;container-name:totp}
.control-page{--totp-line:var(--dsw-alias-border-l2,#0000001a);--totp-muted:var(--dsw-alias-label-tertiary,#979da6)}
.control-page h4,.recovery-heading h4{font-size:14px;font-weight:550;line-height:1.5;margin:0}.control-page p{margin:0}
.page-heading{margin-bottom:20px}.page-kicker{display:block;color:var(--dsw-alias-label-secondary,#61666b);font-size:11px;font-weight:600;letter-spacing:.13em;margin-bottom:6px}.page-heading h3{font-size:26px;letter-spacing:-.55px;margin-bottom:8px}.page-heading>p{font-size:13px;color:var(--dsw-alias-label-secondary,#61666b)}
.protection-card{border:1px solid var(--totp-line);border-radius:18px;padding:18px 20px;background:var(--dsw-alias-bg-layer-1,#fff);background:radial-gradient(ellipse at 100% 0,color-mix(in srgb,var(--dsw-alias-label-primary,#0f1115) 5%,transparent),transparent 65%),var(--dsw-alias-bg-layer-1,#fff)}
.protection-top,.protection-bottom{display:flex;align-items:center;justify-content:space-between;gap:16px}.section-kicker{font-size:12px;font-weight:500;color:var(--dsw-alias-label-secondary,#61666b)}
.state-pill{display:inline-flex;gap:6px;align-items:center;border:1px solid var(--totp-line);border-radius:99px;padding:3px 9px;font-size:11px;white-space:nowrap;color:var(--dsw-alias-label-secondary,#61666b)}.state-pill i{width:5px;height:5px;border:1px solid currentColor;border-radius:50%}.state-pill[data-enabled=true]{color:var(--dsw-alias-label-primary,#0f1115);background:var(--dsw-alias-button-ghost-active-fill,#ebeef2)}.state-pill[data-enabled=true] i{background:currentColor}
.protection-body{display:flex;gap:16px;align-items:center;margin:16px 0}.protection-symbol{display:grid;place-items:center;flex:0 0 48px;height:48px;border:1px solid var(--totp-line);border-radius:16px;background:var(--dsw-alias-bg-layer-2,#fff);box-shadow:0 4px 12px #00000008}.protection-symbol svg{width:28px;height:28px}.protection-body h4{font-size:20px;font-weight:550;letter-spacing:-.35px;margin-bottom:6px}.protection-body p{font-size:12px;line-height:1.7;color:var(--dsw-alias-label-secondary,#61666b)}
.protection-bottom{padding-top:12px;border-top:1px solid var(--totp-line)}.protection-bottom>span{font-size:11px;color:var(--totp-muted)}.protection-bottom b{font-weight:400;margin:0 5px}.protection-bottom button{min-height:32px;padding:5px 12px;font-size:12px}
.credentials-section{margin-top:22px}.section-title{margin-bottom:12px!important}.credential-list{border:1px solid var(--totp-line);border-radius:14px;overflow:hidden}.credential-row{display:grid;grid-template-columns:22px minmax(0,1fr) auto;align-items:center;gap:13px;padding:14px 16px;transition:background .15s}.credential-row+.credential-row{border-top:1px solid var(--totp-line)}.credential-row:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#0f1115) 2%,transparent)}.row-symbol{display:grid;place-items:center;color:var(--dsw-alias-label-secondary,#61666b)}.row-symbol svg{width:21px;height:21px}.credential-copy strong{font-size:13px;font-weight:550;display:flex;align-items:center;gap:8px}.credential-copy p{font-size:11px;color:var(--totp-muted);margin-top:4px;line-height:1.6}.subtle-badge{font-size:10px;font-weight:400;color:var(--totp-muted)}
.quiet-button{border-color:transparent;background:transparent;font-size:12px;min-height:32px;padding:6px 8px;white-space:nowrap}.quiet-button:hover{background:var(--dsw-alias-button-floating-hover,#f3f4f6)}
.lock-section{display:grid;grid-template-columns:22px minmax(0,1fr) auto;align-items:center;gap:13px;margin-top:20px;padding-top:18px;border-top:1px solid var(--totp-line)}.lock-section h4{font-size:12px}.lock-section p{font-size:11px;color:var(--totp-muted);margin-top:4px}.lock-section button{font-size:12px;min-height:34px;padding:7px 11px;white-space:nowrap}.panel-dismiss{margin-top:20px}.panel-dismiss:has(button[hidden]){display:none}
.authorization-card{margin-top:16px;padding:20px;border:1px solid var(--totp-line);border-radius:14px;background:var(--dsw-alias-bg-layer-1,#fff);animation:totp-reveal .18s ease-out}.authorization-card>header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.authorization-card h4{margin-top:3px;font-size:15px}.icon-button{border:0;background:transparent;min-height:28px;width:28px;padding:5px;display:grid;place-items:center}.icon-button svg{width:16px;height:16px}.field-note{font-size:11px;line-height:1.7;color:var(--totp-muted);margin-top:10px!important}.authorization-card .error:empty{display:none}
.quick-actions button{display:flex;align-items:center;gap:6px;border-radius:11px;font-size:12px;padding:7px 11px;min-height:34px;box-shadow:0 3px 12px #00000010}.quick-actions svg{width:14px;height:14px}
.lock-shortcut{position:relative;display:block;border-radius:11px}.lock-shortcut:focus-visible{outline:2px solid var(--dsw-alias-label-tertiary,#979da6);outline-offset:3px}.lock-shortcut:has(button:disabled){cursor:not-allowed}.lock-shortcut button:disabled{pointer-events:none;color:var(--dsw-alias-label-tertiary,#979da6);box-shadow:none}.lock-hint{position:absolute;right:0;bottom:calc(100% + 10px);width:max-content;max-width:calc(100vw - 36px);padding:9px 12px;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:10px;background:var(--dsw-alias-bg-layer-2,#fff);color:var(--dsw-alias-label-secondary,#61666b);font-size:12px;line-height:1.6;box-shadow:0 4px 16px #00000010;visibility:hidden;pointer-events:none}.lock-shortcut:hover .lock-hint,.lock-shortcut:focus-within .lock-hint{visibility:visible}.lock-error{font-size:12px;line-height:1.6;color:var(--totp-error,var(--dsw-static-red-500,#ef4444));margin:8px 0 0;max-width:280px}.lock-error:empty{display:none}.quick-actions>.lock-error{position:absolute;right:0;bottom:calc(100% + 10px);width:max-content;max-width:calc(100vw - 36px);padding:9px 12px;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:10px;background:var(--dsw-alias-bg-layer-2,#fff);box-shadow:0 4px 16px #00000010}
.recovery-panel{margin-top:20px;padding:18px;border:1px solid var(--totp-line);border-radius:14px;background:var(--dsw-alias-bg-layer-1,#fff);animation:totp-reveal .18s ease-out}.recovery-heading{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.recovery-heading p{font-size:11px;color:var(--dsw-alias-label-secondary,#61666b);margin:4px 0 0}.recovery-heading button{font-size:11px;padding:5px 9px;min-height:30px;white-space:nowrap}.recovery-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 12px;margin:0;padding:0;list-style:none}.recovery-grid li{display:flex;align-items:flex-start;gap:8px;padding:8px 0;border-bottom:1px solid var(--dsw-alias-border-l2,#0000001a)}.recovery-number{font:10px/1.8 ui-monospace,monospace;color:var(--dsw-alias-label-tertiary,#979da6)}.recovery-grid code{font:11px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;min-width:0}.copy-status{font-size:11px;color:var(--dsw-alias-label-secondary,#61666b);margin:10px 0 0}.copy-status:empty{display:none}
.enrollment-steps{display:flex;list-style:none;padding:0;margin:0 0 26px;gap:16px}.enrollment-steps li{display:flex;align-items:center;gap:6px;color:var(--dsw-alias-label-tertiary,#979da6);font-size:11px;white-space:nowrap}.enrollment-steps span{width:20px;height:20px;display:grid;place-items:center;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:50%;font:10px ui-monospace,monospace}.enrollment-steps li[data-state=active]{color:var(--dsw-alias-label-primary,#0f1115)}.enrollment-steps li[data-state=active] span{color:var(--dsw-alias-label-primary-foreground,#fff);background:var(--dsw-alias-button-primary-fill,#0f1115);border-color:transparent}.enrollment-steps li[data-state=complete] span{background:var(--dsw-alias-button-ghost-active-fill,#ebeef2)}
.enrollment-surface{padding:24px;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:16px;background:var(--dsw-alias-bg-layer-1,#fff)}.enrollment-surface h3{font-size:22px;letter-spacing:-.35px}.enrollment-surface .binding-note{font-size:12px;line-height:1.8;margin-bottom:0}.enrollment-qr{display:grid;place-items:center;padding:24px 0}.enrollment-surface .qr{margin:0;border-radius:14px;box-shadow:0 6px 20px #00000010}.otp-form{width:min(100%,420px);margin:24px auto 0;container-type:inline-size;container-name:otp-field}.enrollment-qr+.otp-form{margin-top:0;padding-top:20px;border-top:1px solid var(--dsw-alias-border-l2,#0000001a)}.otp-label-row{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:10px}.otp-label-row label{margin:0;font-size:13px;font-weight:500;color:var(--dsw-alias-label-primary,#0f1115)}.otp-label-row>span{font-size:11px;white-space:nowrap;color:var(--dsw-alias-label-tertiary,#979da6)}.otp-help{font-size:12px;line-height:1.7;color:var(--dsw-alias-label-secondary,#61666b);margin:10px 0 0}.otp-form .actions{margin-top:20px}.otp-form .primary{width:100%;min-height:46px;border-radius:12px;font-size:14px;font-weight:500}.enrollment-surface .error:empty{display:none}.enrollment-surface>.error{width:min(100%,420px);margin:14px auto 0}.enrollment-complete{display:inline-grid;place-items:center;width:38px;height:38px;border:1px solid var(--dsw-alias-border-l2,#0000001a);border-radius:12px;font-size:20px;margin-bottom:16px;background:var(--dsw-alias-bg-layer-2,#fff)}
@container totp (max-width:420px){.enrollment-surface{padding:20px}.enrollment-qr{padding:20px 0}.otp-label-row{gap:8px}.otp-label-row>span{font-size:10px}}
@media(max-height:780px){.enrollment-steps{margin-bottom:20px}.enrollment-surface{padding:20px}.enrollment-qr{padding:20px 0}.enrollment-qr .qr{width:192px;height:192px}.enrollment-qr+.otp-form{padding-top:16px}input.code{height:68px}.otp-form .actions{margin-top:16px}.otp-form .primary{min-height:44px}}
@container otp-field (max-width:340px){input.code{height:68px;font-size:30px}.otp-label-row{gap:8px}.otp-label-row>span{font-size:10px}}
@keyframes totp-reveal{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}
@container totp (max-width:420px){.protection-card{padding:18px}.protection-body{gap:12px}.protection-body h4{font-size:18px}.credential-row{grid-template-columns:20px minmax(0,1fr);padding:16px 14px}.credential-row>.quiet-button{grid-column:2;justify-self:start;margin-left:-8px;margin-top:-4px}.lock-section{grid-template-columns:20px minmax(0,1fr)}.lock-section>button{grid-column:2;justify-self:start}.recovery-grid{grid-template-columns:1fr}.enrollment-steps{gap:10px}.enrollment-steps li{font-size:10px}}
@media(max-width:480px){dialog{padding:22px}.actions button{min-height:42px}.qr{width:208px;height:208px}.recovery-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){button,.credential-row{transition:none}.authorization-card,.recovery-panel{animation:none}}`;

export const portalCss = `${portalTheme}\n${panelCss}
html{font:14px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:24px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}main{width:min(100%,488px);padding:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:20px;background:var(--dsw-alias-bg-layer-2)}h1{font-size:24px;font-weight:600;letter-spacing:-.4px;margin:0 0 10px}main>p{color:var(--dsw-alias-label-secondary)}form>button.primary{width:100%;margin-top:18px}.footer{font-size:12px;color:var(--dsw-alias-label-tertiary);margin-top:24px}.text-button{border:0;padding:0;min-height:24px;background:transparent!important;color:var(--dsw-alias-label-secondary)}.help{font-size:13px;color:var(--dsw-alias-label-secondary);margin:18px 0 0}`;
